- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: be sure firewalld is disabled
      systemd: name=firewalld enabled=no

    - name: be sure firewalld is stopped
      systemd: name=firewalld state=stopped

    - name: be sure docker is started
      systemd: name=docker state=started enabled=yes

    - name: Set bridge-nf-call-{arptables,iptables} to 1
      sysctl:
        name: "{{ item }}"
        state: present
        value: 1
        sysctl_file: /etc/sysctl.d/bridge-nf-call.conf
        reload: yes
      with_items:
        - net.bridge.bridge-nf-call-iptables

    - name: configure Docker to use systemd cgroup
      copy:
              dest: /etc/docker/daemon.json
              src: daemon.json

    - name: restart Docker
      systemd: name=docker state=restarted

    - name: Remove swapfile from /etc/fstab
      mount:
         name: swap
         fstype: swap
         state: absent
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
